export enum RoomAmenity {
  PROJECTOR = 'PROJECTOR',
  WHITEBOARD = 'WHITEBOARD',
  VIDEO_CONFERENCE = 'VIDEO_CONFERENCE',
  PHONE = 'PHONE',
  TV = 'TV',
  WIFI = 'WIFI',
  COFFEE = 'COFFEE',
  PARKING = 'PARKING'
}
