export enum OrderStatus {
  PENDING = 'PENDING',
  SENT_TO_EXCHANGE = 'SENT_TO_EXCHANGE',
  EXECUTED = 'EXECUTED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  PARTIALLY_EXECUTED = 'PARTIALLY_EXECUTED'
}
