export enum ReportType {
  PNL_STATEMENT = 'PNL_STATEMENT',
  TAX_REPORT = 'TAX_REPORT',
  TRADE_HISTORY = 'TRADE_HISTORY',
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',
  PORTFOLIO_SUMMARY = 'PORTFOLIO_SUMMARY',
  HOLDINGS_REPORT = 'HOLDINGS_REPORT'
}
