export enum QuotaType {
  GENERAL = 'GENERAL',
  TATKAL = 'TATKAL',
  LADIES = 'LADIES',
  SENIOR_CITIZEN = 'SENIOR_CITIZEN',
  LOWER_BERTH = 'LOWER_BERTH',
  PHYSICALLY_HANDICAPPED = 'PHYSICALLY_HANDICAPPED',
  DEFENCE = 'DEFENCE',
  PREMIUM_TATKAL = 'PREMIUM_TATKAL'
}
