export enum TrainType {
  SUPERFAST_EXPRESS = 'SUPERFAST_EXPRESS',
  MAIL_EXPRESS = 'MAIL_EXPRESS',
  RAJDHANI = 'RAJDHANI',
  SHATABDI = 'SHATABDI',
  DURONTO = 'DURONTO',
  GARIB_RATH = 'GARIB_RATH',
  INTERCITY = 'INTERCITY',
  PASSENGER = 'PASSENGER',
  LOCAL = 'LOCAL'
}
