export enum Amenity {
  LIFT = 'LIFT',
  CCTV = 'CCTV',
  SECURITY_GUARD = 'SECURITY_GUARD',
  GATED_COMMUNITY = 'GATED_COMMUNITY',
  BALCONY = 'BALCONY',
  MODULAR_KITCHEN = 'MODULAR_KITCHEN',
  AC = 'AC',
  GEYSER = 'GEYSER',
  WIFI = 'WIFI',
  PARKING = 'PARKING',
  POWER_BACKUP = 'POWER_BACKUP',
  WATER_SUPPLY = 'WATER_SUPPLY',
  OTHER = 'OTHER'
}
